# ---------------------------------------------------------------
# ICON Settings 图标设置
# ---------------------------------------------------------------

favicon: https://i.cssj.fun/usr/hugo/favicon.png
avatar: https://i.cssj.fun/usr/hugo/1436431885.jpg
apple_icon:
  # iPhone 57x57 
  iphone: https://imgur.lzmun.com/picgo/20200430223748.jpg_iPhone
  # iPad 72x72
  ipad: https://imgur.lzmun.com/picgo/20200430223748.jpg_RetinaiPad
  # Retina iPhone 114x114
  iphone_hd: https://imgur.lzmun.com/picgo/20200430223748.jpg_iPhoneHD
  # Retina iPad 144x144
  ipad_hd: https://imgur.lzmun.com/picgo/20200430223748.jpg_RetinaiPad
  
# ---------------------------------------------------------------
# Style Settings 样式设置
# ---------------------------------------------------------------

# Schemes
schemes: column

# Random Pictures
random_pic_switch: true
random_pics: 19
random_thumbnail: ../img/random/randompic-

# ---------------------------------------------------------------
# Header and Nav Settings 页眉、导航和封面设置
# ---------------------------------------------------------------

# Header Cover
header: 
  img: https://i.cssj.fun/usr/hugo/pexels-flora-westbrook-5221808.jpg
  title_color: '#fff'

drawer_header: //imgur.lzmun.com/picgo/20200405182517.jpg

# Header Links
search_btn: true
nav:
  首页:
    link: /
    icon: home
  归档: 
    link: /archives/
    icon:   move_to_inbox
  关于:
    link: /about.html
    icon: person
  友链:
    link: /links.html
    icon: link
  说说:
    link: /bb
    icon: bb

# Materiac ICON from https://www.mdui.org/docs/material_icon

# ---------------------------------------------------------------
# Footer Settings 页脚设置
# ---------------------------------------------------------------

start_time: 2016
count: true
icp: 晋ICP备18002380号

# CDN LOGO
# Use upyun
cdn: 
  use: upyun
  upyun: 
    src: https://i.cssj.fun/usr/hugo/%E5%8F%88%E6%8B%8D%E4%BA%91_logo5.png

# ---------------------------------------------------------------
# Index Settings 首页设置
# ---------------------------------------------------------------

# Social link 社交链接
social_link:
  use: true
  wechat_personal: 
    switch: true
    src: https://i.cssj.fun/usr/hugo/weixin.jpg
  wechat_public: 
    switch: true
    src: https://open.weixin.qq.com/qr/code?username=p0o8o0q

# ---------------------------------------------------------------
# Posts Settings 文章设置
# ---------------------------------------------------------------

# Post
default_post_title: Untitled
auto_excerpt:
  length: 120

# highlight.js 代码高亮
# style github | tomorrow  | night-blue | night-bright | night-eighties
highlight:
  use: true
  style: night-bright

# ---------------------------------------------------------------
# Third Party Services Settings 第三方服务设置
# ---------------------------------------------------------------

# Comment 评论
# Use gitment | valine | disqus | disqusjs | gitalk
comment:
  use: disqus
  gitment:
    owner:
    repo:
    client_id:
    client_secret:
  valine:
    appid: 
    appkey: 
  disqus:
    src: chensu8
    # such as: https://xxx.disqus.com/embed.js
  disqusjs:
    shortname: 
    siteName: 
    api: 
    apikey: 
    admin: 
    adminLabel: 
  gitalk:
    clientID: 
    clientSecret: 
    repo: 
    owner: 
    admin: 
    distractionFreeMode: 

# Busuanzi Count 不蒜子计数
busuanzi: false

# Google Analytics 谷歌分析
# cloudflare-workers-async-google-analytics
# if use is default, it will use analytics.js
# if use is cf_async, look at the https://github.com/SukkaW/cloudflare-workers-async-google-analytics to learn more
# 如果 use 项选择 default，将使用 analytics.js 文件接入谷歌分析
# 如果 use 项目选择 cf_async，请浏览 https://github.com/SukkaW/cloudflare-workers-async-google-analytics 进行配置

google_analytics:
  # use: default
  use: default
  ga_id: 
  ga_api: 

# chart.js
# https://www.chartjs.org/
chart_js:
  use: false

